### ISSUE TITLE
is it possible to use fasta files from different assembly softwares to create a circular fasta

### ISSUE THREAD

**Issue by LuffyLuffy** [jfass/apc#3]
Hi,
apc.pl is fast to tell whether a single sequence  is a circular chromosome or plasmid.  
I wonder if it possible to use different assembly result to realize a circular fasta file, that is, gap closer by different assembly results.
Presently, we use paired blast and based on the blast result, to extend the fasta file, and finally got a circular chromosome.

**Comment by jfass** [comment]
I think there are better tools to do that kind of thing, like the [PB-Suite](https://sourceforge.net/projects/pb-jelly/) ... or [Circlator](https://github.com/sanger-pathogens/circlator)? ... though I don't have any direct experience with the latter. I hope that helps.

I don't have immediate plans to improve apc, but I'll keep your suggestion in mind if I do!
~Joe
